=== Tagarela76/voc/vwm/modules/tests/_files/bridge/bridge.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<xs:element name="bridge">
<xs:complexType>
  <xs:sequence>
    <xs:element name="customers">
        <xs:complexType>
            <xs:sequence>
            <xs:element name="customer" type="customerinfo" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="limits">
        <xs:complexType>
            <xs:sequence>
            <xs:element name="limit" type="limitinfo" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
            
    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
            <xs:element name="user" type="userinfo" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
  </xs:sequence>
</xs:complexType>
</xs:element>

<xs:complexType name="customerinfo">
 <xs:sequence>
    <xs:element name="name" type="xs:string" default=""/>
    <xs:element name="address" type="xs:string" default=""/>
    <xs:element name="city" type="xs:string" default=""/>
    <xs:element name="zip" type="xs:string" default=""/>
    <xs:element name="state" type="xs:positiveInteger"/>
    <xs:element name="country" type="xs:positiveInteger"/>
    <xs:element name="county" type="xs:string" default=""/>
    <xs:element name="phone" type="xs:string" default=""/>
    <xs:element name="fax" type="xs:string" default=""/>
    <xs:element name="email" type="xs:string" default=""/>
    <xs:element name="contact" type="xs:string" default=""/>
    <xs:element name="title" type="xs:string" default=""/>
    <xs:element name="trial_end_date" type="xs:date"/>
    <xs:element name="period_end_date" type="xs:date"/>
    <xs:element name="deadline_counter" type="xs:integer"/>
    <xs:element name="status" type="enumStatus"/>
    <xs:element name="limit" type="customerlimit" minOccurs="0" maxOccurs="unbounded"/>
 </xs:sequence>
 <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
</xs:complexType>

<xs:simpleType name="enumStatus">
  <xs:restriction base="xs:string">
    <xs:enumeration value="on"/>
    <xs:enumeration value="off"/>
  </xs:restriction>
</xs:simpleType>

<xs:complexType name="customerlimit">
  <xs:sequence>
    <xs:element name="limit_id" type="xs:positiveInteger"/>
    <xs:element name="current_value" type="xs:decimal"/>
    <xs:element name="max_value" type="xs:decimal"/>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="limitinfo">
 <xs:sequence>
    <xs:element name="name" type="xs:string"/>
    <xs:element name="increase_step" type="xs:decimal"/>
    <xs:element name="unit_type" type="xs:string" default=""/>
    <xs:element name="type" type="xs:string"/>
 </xs:sequence>
 <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
</xs:complexType>

<xs:complexType name="userinfo">
 <xs:sequence>
    <xs:element name="username" type="xs:string"/>
    <xs:element name="accessname" type="xs:string"/>
    <xs:element name="password" type="xs:string"/>
    <xs:element name="email" type="xs:string"/>
    <xs:element name="phone" type="xs:string"/>
    <xs:element name="accesslevel_id" type="xs:nonNegativeInteger"/>
    <xs:element name="company_id" type="xs:nonNegativeInteger"/>
    <xs:element name="facility_id" type="xs:nonNegativeInteger" default="0"/>
    <xs:element name="department_id" type="xs:nonNegativeInteger" default="0"/>
 </xs:sequence>
 <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
</xs:complexType>

</xs:schema>

=== Tagarela76/voc/vwm/modules/tests/acceptance/vps/bridge/bridge.xml
<?xml version="1.0" encoding="UTF-8"?>
<bridge xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bridge.xsd">
  <customers>
    <customer id="114">
      <name>VOCWEBMANAGER DEV</name>
      <address>Address</address>
      <city>City</city>
      <zip>13132</zip>
      <state>137</state>
      <country>215</country>
      <county>County</county>
      <phone>5555</phone>
      <fax>5555</fax>
      <email>denis.nt@kttsoft.com</email>
      <contact>Denis Tukalenko</contact>
      <title>acceptance test</title>
      <trial_end_date>2010-01-01</trial_end_date>
      <period_end_date>2010-01-01</period_end_date>
      <deadline_counter>NULL</deadline_counter>
      <status>off</status>
      <limit>
        <limit_id>1</limit_id>
        <current_value>0</current_value>
        <max_value>50</max_value>
      </limit>
      <limit>
        <limit_id>2</limit_id>
        <current_value>0</current_value>
        <max_value>300</max_value>
      </limit>
      <limit>
        <limit_id>3</limit_id>
        <current_value>2</current_value>
        <max_value>2</max_value>
      </limit>
    </customer>
  </customers>
  <limits>
    <limit id="1">
      <name>MSDS</name>
      <increase_step>10</increase_step>
      <unit_type/>
      <type>limit</type>
    </limit>
    <limit id="2">
      <name>memory</name>
      <increase_step>100</increase_step>
      <unit_type>Mb</unit_type>
      <type>limit</type>
    </limit>
    <limit id="3">
      <name>Source count</name>
      <increase_step>1</increase_step>
      <unit_type/>
      <type>bplimit</type>
    </limit>
  </limits>
  <users>
    <user id="62">
      <username>kttsoft</username>
      <accessname>kttsoft</accessname>
      <password>d52b1b1763f67cf1d636d8e4ff11d058</password>
      <email>kttsoft@gmail.com</email>
      <phone>+38 067 7218938</phone>
      <accesslevel_id>3</accesslevel_id>
      <company_id>0</company_id>
      <facility_id>0</facility_id>
      <department_id>0</department_id>
    </user>
    <user id="70">
      <username>user1</username>
      <accessname>user1</accessname>
      <password>1b111411f1b95cfbf70d3ad478b247d9</password>
      <email>denis.nt@kttsoft.com</email>
      <phone>User1 [1-2]</phone>
      <accesslevel_id>0</accesslevel_id>
      <company_id>114</company_id>
      <facility_id>0</facility_id>
      <department_id>0</department_id>
    </user>
    <user id="72">
      <username>Facility</username>
      <accessname>user1facility</accessname>
      <password>28b904ca567a60a4e647b2502d83746c</password>
      <email>denis.nt@kttsoft.com</email>
      <phone>4242342</phone>
      <accesslevel_id>1</accesslevel_id>
      <company_id>114</company_id>
      <facility_id>0</facility_id>
      <department_id>0</department_id>
    </user>
    <user id="73">
      <username>Department</username>
      <accessname>user1department</accessname>
      <password>4cac0445519cb36fe00fb5e3d0fcc4cb</password>
      <email>denis.nt@kttsoft.com</email>
      <phone>545353</phone>
      <accesslevel_id>2</accesslevel_id>
      <company_id>114</company_id>
      <facility_id>0</facility_id>
      <department_id>0</department_id>
    </user>
  </users>
</bridge>

=== Tagarela76/voc/vwm/modules/tests/_files/bridge/bridgeCreateInvoiceForBillingVar3.xml
<?xml version="1.0" encoding="UTF-8"?>
<bridge xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bridge.xsd">
  <customers>
    <customer id="105">
      <name>Gyant Demo Version</name>
      <address>23974 Aliso Creek Road, Suite 280</address>
      <city>Laguna Niguel</city>
      <zip>92677</zip>
      <state>133</state>
      <country>215</country>
      <county>1</county>
      <phone>949 495-0999</phone>
      <fax>(714) 379-8894</fax>
      <email>test_email@somewhere.com</email>
      <contact>Jon Gypsyn</contact>
      <title>Software Sales</title>
      <trial_end_date>2009-11-16</trial_end_date>
      <period_end_date>2009-12-16</period_end_date>
      <deadline_counter>NULL</deadline_counter>
      <status>on</status>
      <limit>
        <limit_id>1</limit_id>
        <current_value>0</current_value>
        <max_value>50</max_value>
      </limit>
      <limit>
        <limit_id>2</limit_id>
        <current_value>0</current_value>
        <max_value>300</max_value>
      </limit>
      <limit>
        <limit_id>3</limit_id>
        <current_value>0</current_value>
        <max_value>1</max_value>
      </limit>
    </customer>
    <customer id="111">
      <name>TestCompany</name>
      <address>gdfgdf</address>
      <city>hkjhkh</city>
      <zip>74654</zip>
      <state>129</state>
      <country>215</country>
      <county>khkjhk</county>
      <phone>kgh</phone>
      <fax>jg</fax>
      <email>ghjg@o.ia</email>
      <contact>gd</contact>
      <title>dfgfdg</title>
      <trial_end_date>2009-11-16</trial_end_date>
      <period_end_date>2009-11-16</period_end_date>
      <deadline_counter>NULL</deadline_counter>
      <status>off</status>
      <limit>
        <limit_id>1</limit_id>
        <current_value>0</current_value>
        <max_value>50</max_value>
      </limit>
      <limit>
        <limit_id>2</limit_id>
        <current_value>0</current_value>
        <max_value>300</max_value>
      </limit>
      <limit>
        <limit_id>3</limit_id>
        <current_value>0</current_value>
        <max_value>1</max_value>
      </limit>
    </customer>
    <customer id="112">
      <name>ABC</name>
      <address>20, Apple Raoad</address>
      <city>Laguna Niguel</city>
      <zip>92677</zip>
      <state>207</state>
      <country>215</country>
      <county>Orange</county>
      <phone>1234567</phone>
      <fax>9876543</fax>
      <email>a@go.com</email>
      <contact>me</contact>
      <title>o</title>
      <trial_end_date>2009-11-16</trial_end_date>
      <period_end_date>2009-11-16</period_end_date>
      <deadline_counter>NULL</deadline_counter>
      <status>off</status>
      <limit>
        <limit_id>1</limit_id>
        <current_value>0</current_value>
        <max_value>50</max_value>
      </limit>
      <limit>
        <limit_id>2</limit_id>
        <current_value>0</current_value>
        <max_value>300</max_value>
      </limit>
      <limit>
        <limit_id>3</limit_id>
        <current_value>0</current_value>
        <max_value>1</max_value>
      </limit>
    </customer>
    <customer id="113">
      <name>Shmaze Custom Coatings</name>
      <address>20792 Canada Road</address>
      <city>Lake Forest</city>
      <zip>92677</zip>
      <state>133</state>
      <country>215</country>
      <county>Orange</county>
      <phone>949 583 1448</phone>
      <fax>949 583 1263</fax>
      <email>mike@shmaze.com</email>
      <contact>Mike Shmaze</contact>
      <title>CEO</title>
      <trial_end_date>2009-11-16</trial_end_date>
      <period_end_date>2009-11-16</period_end_date>
      <deadline_counter>NULL</deadline_counter>
      <status>off</status>
      <limit>
        <limit_id>1</limit_id>
        <current_value>0</current_value>
        <max_value>50</max_value>
      </limit>
      <limit>
        <limit_id>2</limit_id>
        <current_value>0</current_value>
        <max_value>300</max_value>
      </limit>
      <limit>
        <limit_id>3</limit_id>
        <current_value>0</current_value>
        <max_value>1</max_value>
      </limit>
    </customer>
	<customer id="115">
      <name>Tukalenko Inc</name>
      <address>23974 Aliso Creek Road, Suite 280</address>
      <city>Laguna Niguel</city>
      <zip>92677</zip>
      <state>133</state>
      <country>215</country>
      <county>1</county>
      <phone>949 495-0999</phone>
      <fax>(714) 379-8894</fax>
      <email>test_email@somewhere.com</email>
      <contact>Denis</contact>
      <title>Software Sales</title>
      <trial_end_date>2009-11-16</trial_end_date>
      <period_end_date>2009-12-16</period_end_date>
      <deadline_counter>NULL</deadline_counter>
      <status>on</status>
      <limit>
        <limit_id>1</limit_id>
        <current_value>0</current_value>
        <max_value>75</max_value>
      </limit>
      <limit>
        <limit_id>2</limit_id>
        <current_value>0</current_value>
        <max_value>350</max_value>
      </limit>
      <limit>
        <limit_id>3</limit_id>
        <current_value>0</current_value>
        <max_value>1</max_value>
      </limit>
    </customer>
	<customer id="116">
      <name>Tukalenko Inc Corp</name>
      <address>23974 Aliso Creek Road, Suite 280</address>
      <city>Laguna Niguel</city>
      <zip>92677</zip>
      <state>133</state>
      <country>215</country>
      <county>1</county>
      <phone>949 495-0999</phone>
      <fax>(714) 379-8894</fax>
      <email>test_email@somewhere.com</email>
      <contact>Denis</contact>
      <title>Software Sales</title>
      <trial_end_date>2009-11-16</trial_end_date>
      <period_end_date>2009-12-16</period_end_date>
      <deadline_counter>10</deadline_counter>
      <status>on</status>
      <limit>
        <limit_id>1</limit_id>
        <current_value>0</current_value>
        <max_value>60</max_value>
      </limit>
      <limit>
        <limit_id>2</limit_id>
        <current_value>0</current_value>
        <max_value>300</max_value>
      </limit>
      <limit>
        <limit_id>3</limit_id>
        <current_value>0</current_value>
        <max_value>2</max_value>
      </limit>
    </customer>
  </customers>  
  <limits>
    <limit id="1">
      <name>MSDS</name>
      <increase_step>10</increase_step>
      <unit_type/>
      <type>limit</type>
    </limit>
    <limit id="2">
      <name>memory</name>
      <increase_step>100</increase_step>
      <unit_type>Mb</unit_type>
      <type>limit</type>
    </limit>
    <limit id="3">
      <name>Source count</name>
      <increase_step>1</increase_step>
      <unit_type/>
      <type>bplimit</type>
    </limit>
  </limits>
  <users>
    <user id="1">
      <username>gennadiy</username>
      <accessname>gennadiy</accessname>
      <password>5f4dcc3b5aa765d61d8327deb882cf99</password>
      <email></email>
      <phone></phone>
      <accesslevel_id>0</accesslevel_id>
      <company_id>105</company_id>
      <facility_id>0</facility_id>
      <department_id>0</department_id>
    </user>
    <!--<user id="2">
      <username>Department</username>
      <accessname>department</accessname>
      <password>459d9fca17e3a950deae755d13578292</password>
      <email>department@department.department</email>
      <phone>department</phone>
      <accesslevel_id>2</accesslevel_id>
      <company_id>105</company_id>
      <facility_id>0</facility_id>
      <department_id>0</department_id>
    </user>-->
  </users>
</bridge>
