=== Tagarela76/voc/vwm/regAgency.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="AGENCIES">
        <xs:complexType>
            <xs:sequence>
            <xs:element name="AGENCY" type="AGENCYINFO" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

<xs:complexType name="AGENCYINFO">
 <xs:sequence>
    <xs:element name="NAME" type="xs:string" default=""/>
    <xs:element name="ACRONYM" type="xs:string" default=""/>
    <xs:element name="AGENCY_CODE" type="xs:string" default=""/>
 </xs:sequence>
</xs:complexType>

=== Tagarela76/voc/vwm/regAgency.xml
<?xml version="1.0" encoding="UTF-8"?>
<AGENCIES xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="regAgency.xsd">
<AGENCY>
<NAME>Environmental Protection Agency</NAME>
<ACRONYM>EPA</ACRONYM>
<AGENCY_CODE>2000</AGENCY_CODE>
</AGENCY>
<AGENCY>
<NAME>Regional Office Boston</NAME>
<ACRONYM>ROBOSTON</ACRONYM>
<AGENCY_CODE>2001</AGENCY_CODE>
</AGENCY>
<AGENCY>
<NAME>Regional Office New York</NAME>
<ACRONYM>RONEWYORK</ACRONYM>
<AGENCY_CODE>2002</AGENCY_CODE>
</AGENCY>
<AGENCY>
<NAME>Regional Office Philadelphia</NAME>
<ACRONYM>ROPHILA</ACRONYM>
<AGENCY_CODE>2003</AGENCY_CODE>
</AGENCY>
<AGENCY>
<NAME>Regional Office Atlanta</NAME>
<ACRONYM>ROATLANTA</ACRONYM>
<AGENCY_CODE>2004</AGENCY_CODE>
</AGENCY>
<AGENCY>
<NAME>Regional Office Chicago</NAME>
<ACRONYM>ROCHICAGO</ACRONYM>
<AGENCY_CODE>2005</AGENCY_CODE>
</AGENCY>
<AGENCY>
<NAME>Regional Office Dallas</NAME>
<ACRONYM>RODALLAS</ACRONYM>
<AGENCY_CODE>2006</AGENCY_CODE>
</AGENCY>
<AGENCY>
<NAME>Regional Office Kansas City</NAME>
<ACRONYM>ROKANSASCITY</ACRONYM>
<AGENCY_CODE>2007</AGENCY_CODE>
</AGENCY>
<AGENCY>
<NAME>Regional Office Denver</NAME>
<ACRONYM>RODENVER</ACRONYM>
<AGENCY_CODE>2008</AGENCY_CODE>
</AGENCY>
<AGENCY>
<NAME>Regional Office San Francisco</NAME>
<ACRONYM>ROSANFRAN</ACRONYM>
<AGENCY_CODE>2009</AGENCY_CODE>
</AGENCY>
<AGENCY>
<NAME>Office of Policy, Economics and Innovation</NAME>
<ACRONYM>PEI</ACRONYM>
<AGENCY_CODE>2010</AGENCY_CODE>
</AGENCY>
<AGENCY>
<NAME>Regional Office Seattle</NAME>
<ACRONYM>ROSEATTLE</ACRONYM>
<AGENCY_CODE>2012</AGENCY_CODE>
</AGENCY>
<AGENCY>
<NAME>Office of General Counsel</NAME>
<ACRONYM>OGC</ACRONYM>
<AGENCY_CODE>2015</AGENCY_CODE>
</AGENCY>
<AGENCY>
<NAME>Office of Enforcement and Compliance Assurance</NAME>
<ACRONYM>OECA</ACRONYM>
<AGENCY_CODE>2020</AGENCY_CODE>
</AGENCY>
<AGENCY>
<NAME>Office of Environmental Information</NAME>
<ACRONYM>OEI</ACRONYM>
<AGENCY_CODE>2025</AGENCY_CODE>
</AGENCY>
<AGENCY>
<NAME>Administration and Resources Management</NAME>
<ACRONYM>ARM</ACRONYM>
<AGENCY_CODE>2030</AGENCY_CODE>
</AGENCY>
<AGENCY>
<NAME>Water</NAME>
<ACRONYM>WATER</ACRONYM>
<AGENCY_CODE>2040</AGENCY_CODE>
</AGENCY>
<AGENCY>
<NAME>Solid Waste and Emergency Response</NAME>
<ACRONYM>SWER</ACRONYM>
<AGENCY_CODE>2050</AGENCY_CODE>
</AGENCY>
<AGENCY>
<NAME>Air and Radiation</NAME>
<ACRONYM>AR</ACRONYM>
<AGENCY_CODE>2060</AGENCY_CODE>
</AGENCY>
<AGENCY>
<NAME>Office of Prevention, Pesticides and Toxic Substances</NAME>
<ACRONYM>OPPTS</ACRONYM>
<AGENCY_CODE>2070</AGENCY_CODE>
</AGENCY>
<AGENCY>
<NAME>Office of Research and Development</NAME>
<ACRONYM>RD</ACRONYM>
<AGENCY_CODE>2080</AGENCY_CODE>
</AGENCY>
<AGENCY>
<NAME>Office of the Administrator</NAME>
<ACRONYM>AdmO</ACRONYM>
<AGENCY_CODE>2090</AGENCY_CODE>
</AGENCY>
</AGENCIES>
